config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :authors, only: [:show, :destroy]
  resources :books, only: [:new, :create, :index, :destroy]
  resources :reviews, only: [:show, :update, :edit, :destroy]
  resources :users

  resources :books, only: [:show, :update, :edit] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many  :book_authors
  has_many :books, through: :book_authors

  validates_presence_of :name
  validates :name, uniqueness: { case_sensitive: false }

  def delete_books(books)
    books.each do |book|
      book.delete_reviews(book.reviews)
      book.delete
    end
  end

end

app/models/book.rb
class Book < ApplicationRecord
  has_many  :book_authors
  has_many :authors, through: :book_authors
  has_many :reviews
  has_many :users, through: :reviews

  validates_presence_of :title, :year, :authors
  validates :length, presence: true, numericality: {
    greater_than_or_equal_to: 0 }
  validates :title, uniqueness: { case_sensitive: false }

  def delete_reviews(reviews)
    reviews.each do |review|
      review.delete
    end
  end

  def average_rating
    reviews.average(:rating).to_f.round(1)
  end

  def total_reviews
    reviews.count
  end

  def self.sort_books_by(column, direction, number = Book.count)
    if column == "length"
      order("#{column} #{direction}")
    else
      Book.sort_by_review(column, direction, number)
    end
  end

  def self.sort_by_review(column, direction, number)
    Book.joins(:reviews)
    .select('books.*, avg(reviews.rating) as average_rating, count(reviews) as reviews_count')
    .group("id")
    .order("#{column} #{direction}, title")
    .limit(number)
  end

  def three_top_or_bottom_reviews(direction)
    reviews.order("rating #{direction}").limit(3)
  end

  def highest_review(reviews)
    reviews.max_by(&:rating)
  end

end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to  :book
  belongs_to  :author
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates_presence_of :title, :description, :book_id
  validates :rating, presence: true, numericality: {
    greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :books, through: :reviews


  validates_presence_of :name
  validates :name, uniqueness: { case_sensitive: false }

  def self.top_three_reviewers
    User.joins(:reviews)
    .select('users.*, count(reviews.id) as reviews_count')
    .group("id")
    .order("reviews_count DESC")
    .limit(3)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find_by(id: params[:id])
  end

  def destroy
    author = Author.find_by(id: params[:id])
    author.delete_books(author.books)
    author.destroy
    redirect_to books_path
  end

end

app/controllers/books_controller.rb
  class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
  end

  def index
    if params[:column]
      @books = Book.sort_books_by(params[:column], params[:direction])
    else
      @books = Book.all
    end
    @users = User.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(merged_params)
    @book.authors = params[:book][:authors].split(",").map do |author|
      Author.find_or_create_by(name: author.titleize.strip)
    end
    if @book.save
      flash[:success] = "Your book has been saved."
      redirect_to book_path(@book)
    else
      flash[:alert] = "Your book could not be saved. Please enter all required fields."
      redirect_to new_book_path(@book)
    end
  end

  def destroy
    book = Book.find_by(id: params[:id])
    book.delete_reviews(book.reviews)
    book.destroy
    redirect_to books_path
  end

private

  def book_params
    params.require(:book).permit(:title, :length, :year, :cover_image, :author)
  end

  def merged_params
    default_image = {:cover_image=>"https://rmnetwork.org/newrmn/wp-content/uploads/2011/11/generic-book-cover.jpg"}

    if params[:book][:cover_image] == ""
      book_params.merge(default_image)
    else
      book_params
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end

  def create
    @book = Book.find(params[:book_id])
    @user = User.find_or_create_by(name: review_params[:user].titleize)
    @review = @book.reviews.create(title: review_params[:title], user: @user, rating: review_params[:rating], description: review_params[:description] )

    if @review.save
      flash[:success] = "Your review has been created."
      redirect_to book_path(@book)
    else
      flash[:alert] = "Your review could not be saved. Please enter all required fields."
      redirect_to new_book_review_path(@book)
    end
  end

  def destroy
    review = Review.find_by(id: params[:review])
    user = User.find_by(id: params[:id])
    review.destroy
    redirect_to user_path(user)
  end

  private

    def review_params
      params.require(:review).permit(:title, :description, :rating, :user)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    if params[:sort]
      if params[:sort] == "desc"
        @reviews = @user.reviews.order(created_at: :desc)
      elsif params[:sort] == "asc"
        @reviews = @user.reviews.order(created_at: :asc)
      end
    else
      @reviews = @user.reviews
    end
  end

  def new
  end

  def create
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/show.html.erb
<!---Header/link panel--->
<header class="index-header">
  <h1><%= @author.name %></h1>
  <div class="links">
    <p class="link"><%= link_to 'Delete This Author', author_path(@author), method: :delete %></p>
  </div>
</header>

<!---Book Panels--->
<div class="container-fluid">
  <% @author.books.each do |book| %>
    <section class="row" id="book-<%=book.id%>">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong id="book-header"><%= link_to book.title, book_path(book) %></strong>
        </div>
        <div class="panel-body author-book-section">
          <div class="book-image">
            <img class="index-cover" src=" <%= book.cover_image %>" alt=" <%= book.title %> image">
          </div>
          <div class="book-data">
            <p id="length-line">Length: <%= book.length %> </p>
            <p>Year: <%= book.year %> </p>
            <p><% if book.authors.count > 1 %> Co-Author(s):
              <% book.authors.each do |book_author| %>
                  <%= book_author.name  if @author.name != book_author.name%>
              <% end %></p>
          <% end %>
          </div>
          <div class="top-review">
            <h3> Highest Review: </h3>
            <% if book.reviews.count > 0 %>
              <% review = book.highest_review(book.reviews) %>
              <p>Title: <%= review.title %></p>
              <p>Description: <%= review.description %></p>
              <p>Rating: <%= review.rating %></p>
              <p>User: <a href=<%=user_path(review.user)%> ><%= review.user.name %></a></p>
            <% else %> <p> Be the first to <%= link_to 'review this book!', new_book_review_path(book) %></p>
            <% end %>
          </div>
        </div>
      </div>
    </section>
  <% end %>
</div>

app/views/books/index.html.erb
<!---Header/link panel--->
<header class="index-header">
  <h1>All Books</h1>
  <div class="links">
    <p class="link"><%= link_to 'Add a New Book', new_book_path %></p>
    <!---Drowndown Sort Menu--->
    <div class="dropdown  dd-sort link">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Sort Books
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="/books?column=average_rating&direction=DESC">Highest Rated</a><br/>
        <a class="dropdown-item" href="/books?column=average_rating&direction=ASC">Lowest Rated</a><br/>
        <a class="dropdown-item" href="/books?column=length&direction=ASC">Shortest First</a><br/>
        <a class="dropdown-item" href="/books?column=length&direction=DESC">Longest First</a><br/>
        <a class="dropdown-item" href="/books?column=reviews_count&direction=DESC">Most Reviewed</a><br/>
        <a class="dropdown-item" href="/books?column=reviews_count&direction=ASC">Least Reviewed</a>
      </div>
    </div>
  </div>
</header>

<!---Book Panels--->
<div class="col-sm-8">
  <% @books.each do |book| %>
    <section class="row" id="book-<%=book.id%>">
      <div class="panel panel-default" id="<%=book.title%>">
        <div class="panel-heading">
          <strong id="book-header"><%= link_to book.title, book_path(book) %></strong>
        </div>
        <div class="panel-body">
          <div class="book-image container-fluid">
            <img class="index-cover" src=" <%= book.cover_image %>" alt=" <%= book.title %> image">
          </div>
          <div class="book-data container-fluid">
            <p>Average Rating: <%= book.average_rating %></p>
            <p>Total Reviews: <%= book.total_reviews %></p>
            <p>Length: <%= book.length %> pages</p>
            <p>Year: <%= book.year %> </p>
            <p>Author(s): <% book.authors.each do |author| %> </p>
              <p><a href=<%=author_path(author)%> ><%= author.name %></a></p>
            <% end %>
          </div>
        </div>
      </div>
    </section>
  <% end %>
</div>

<!---Right-side Stats Panel--->
<div class="col-sm-4">
  <div class="panel panel-default">
    <div class="panel panel-heading">
      <strong id="book-header">Book Stats</strong>
    </div>
    <div class="panel panel-body">
      <footer class ="statistics-footer">
        <div class="statistics-column-1">
          <h4 class="column_title">Top Rated Books</h4>
          <% @books.sort_books_by("average_rating", "DESC", 3).each do |top_book| %>
            <p><%= link_to top_book.title, book_path(top_book) %>: <%=  top_book.average_rating%></p>
          <% end %>
        </div>
        <div class="statistics-column-2">
          <h4 class="column-title">Lowest Rated Books</h4>
          <% @books.sort_books_by("average_rating", "ASC", 3).each do |bottom_book| %>
            <p><%= link_to bottom_book.title, book_path(bottom_book) %>: <%=  bottom_book.average_rating%></p>
          <% end %>
        </div>
        <div class="statistics-column-3">
          <h4 class="column-title">Users With Most Reviews</h4>
          <% @users.top_three_reviewers.each do |top_user| %>
            <p><%= link_to top_user.name, user_path(top_user) %>: <%=  top_user.reviews_count%></p>
          <% end %>
        </div>
      </footer>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<% if @book.errors %>
<ul id="errors">
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<!---Header/link panel--->
<header class="index-header">
  <h1>Add a New Book</h1>
</header>


<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true %>

  <%= f.label :length %>
  <%= f.number_field :length, required: true %>

  <%= f.label :year %>
  <%= f.number_field :year, required: true  %>

  <%= f.label :cover_image%>
  <%= f.text_field :cover_image %>

  <%= f.label :authors %>
  <%= f.text_field :authors, required: true  %>

  <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<!---Header/link panel--->
<header class="index-header">
  <h1><%= @book.title %></h1>
  <div class="links">
    <p class="link"><%= link_to 'Add a New Review', new_book_review_path(@book) %></p>
    <p class="link"><%= link_to 'Delete This Book', book_path(@book), method: :delete %></p>
  </div>
</header>

<!---Book Info Panel--->
<div class="col-sm-8">
  <div class="container-fluid">
    <section class="row">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong id="book-header">Book Info</strong>
        </div>
        <div class="panel-body author-book-section">
          <div class="book-image">
            <img class="index-cover" src="<%= @book.cover_image %>" alt="<%= @book.title %> image">
          </div>
          <div class="top-review">
            <p>Length: <%= @book.length %> pages</p>
            <p>Publication Year: <%= @book.year %></p>
            <p>Author(s): <% @book.authors.each do |author| %> <br/><a href=<%=author_path(author)%>><%= author.name %></a><% end %></p>
          </div>
        </div>
      </div>
    </section>
  </div>
  <div>
    <div class="panel panel-default">
      <div class="panel panel-heading">
        <strong id="book-header">Book Reviews</strong>
      </div>
      <div>
        <% if @book.reviews.count > 0 %>
          <% @book.reviews.each do |review| %>
            <section class="book-review" id="review-<%=review.id%>">
              <p>Description: <%= review.title %> </p>
              <p>Review: <%= review.description %> </p>
              <p>Rating: <%= review.rating %> </p>
              <p>User: <a href=<%=user_path(review.user)%> ><%= review.user.name %></a></p>
            </section>
          <% end %>
        <% else %> <p id="link-message"> Be the first to <%= link_to 'review this book!', new_book_review_path(@book) %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!---Right-side Stats Panel--->
<div class="col-sm-4">
  <div class="panel panel-default">
    <div class="panel panel-heading">
      <strong id="book-header">Book Stats</strong>
    </div>
    <div class="panel panel-body">
      <footer class ="statistics-footer">
        <div class="statistics-column-1">
          <h4 class="column_title">Top Reviews for this Book</h4>
          <% @book.three_top_or_bottom_reviews("DESC").each do |top_review| %>
            <p>"<%= top_review.title %>"</p>
            <li>Rating: <%= top_review.rating %></li>
            <li>User: <%= link_to top_review.user.name, user_path(top_review.user) %></li><br/>
          <% end %>
        </div>
        <div class="statistics-column-2">
          <h4 class="column-title">Lowest Reviews for this Book:</h4>
          <% @book.three_top_or_bottom_reviews("ASC").each do |bottom_review| %>
            <p>"<%= bottom_review.title %>"</p>
            <li>Rating: <%= bottom_review.rating %></li>
            <li>User: <%= link_to bottom_review.user.name, user_path(bottom_review.user) %></li><br/>
          <% end %>
        </div>
        <div class="statistics-column-3">
          <h4 class="column-title">Average Rating for this Book:</h4>
          <p><%= @book.average_rating%></p>
        </div>
      </footer>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BookClub</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/main.css">
  </head>

  <body>
    <div class="container full-body">
      <div class="alert"</div>
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
      </div>
      <div class="container-fluid">
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <div class="navbar-brand">BookClub</div>
            </div>
            <ul class="nav navbar-nav nav-bar">
              <li><%= link_to 'Home', root_path %></li>
              <li><%= link_to 'All Books', books_path %></li>
            </ul>
          </div>
        </nav>
        <div class="container-fluid yield">
          <%= yield %>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reviews/new.html.erb
<% if @review.errors %>
<ul id="errors">
  <% @review.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<!---Header/link panel--->
<header class="index-header">
  <h1>Add a New Review for <%= @book.title %></h1>
</header>

<%= form_for [@book, @review] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true  %>

  <%= f.label :rating %>
  <%= f.number_field :rating, required: true  %>

  <%= f.label :description %>
  <%= f.text_field :description, required: true  %>

  <%= f.label :user %>
  <%= f.text_field :user, required: true %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<!---Header/link panel--->
<header class="index-header">
  <h1><%=@user.name%>'s Reviews</h1>
  <div class="links">
    <div class="link"><%= link_to 'Newest First', user_path(user: @user, sort: 'desc') %></div>
    <div class="link"><%= link_to 'Oldest First', user_path(user: @user, sort: 'asc') %></div>
  </div>
</header>

<!---Book Reviews Panels--->
<div class="container-fluid">
  <% @reviews.each do |review| %>
    <section class="row" id="<%=review.title%>">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong id="book-header"><%= link_to review.book.title, book_path(review.book) %></strong>
        </div>
        <div class="panel-body author-book-section">
          <div class="book-image">
            <img class="index-cover" src=" <%= review.book.cover_image %>" alt=" <%= review.book.title %> image">
          </div>
          <div class="top-review">
            <h3> Review: </h3>
              <p>Title: <%= review.title %></p>
              <p>Description: <%= review.description %></p>
              <p>Rating: <%= review.rating %></p>
              <small>Written on <%= review.created_at.to_date.to_s %></small>
          </div>
        </div>
        <p class="delete-review"><%= link_to 'Delete This Review', review_path(review: review), method: :delete %></p>
      </div>
    </section>
  <% end %>
</div>

app/views/welcome/index.html.erb
<body class="welcome-body">

  <h1 class="welcome-header">Welcome to Book Club</h1>

  <div class="welcome-section">
    <section class="quote">“The only thing that you absolutely have to know, is the location of the library.”<br> - Albert Einstein -</section>

    <section class="github-links">
      <h4>Developed by:</h4>
      <a href="https://github.com/aprildagonese">April Dagonese</a><br>
      <a href="https://github.com/renecasco">Rene Casco</a>
    </section>
  </div>

</body>